version: '3.0'

services:
  mysql:
    image: mysql
    container_name: mysql_database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql-ecommerce:/var/lib/mysql
    networks:
      - ecommerce

volumes:
  mysql-ecommerce:
networks:
  ecommerce:
    driver: bridge
